const gameName = new String('radhika')
console.log(gameName.length)
console.log(gameName.toString())
console.log(gameName.toUpperCase())
console.log(gameName.toLowerCase())
console.log(gameName.charAt(0))
console.log(gameName.charCodeAt(0))
console.log(gameName.indexOf('a'))
console.log(gameName.lastIndexOf('a'))
console.log(gameName.slice(1, 3))
console.log(gameName.substring(1, 3))
console.log(gameName.split(''))
console.log(gameName.concat('Thakur'
))
console.log(gameName.replace('a', 'A'))
console.log(gameName.includes('adhika'))
console.log(gameName.startsWith('ra'))
console.log(gameName.endsWith('ka'))
console.log(gameName.match(/a/g))
console.log(gameName.repeat(3))
console.log(gameName.padStart(10, '0'))
console.log(gameName.padEnd(10, '0'))
console.log(gameName.trim())
console.log(gameName.trimStart())
console.log(gameName.trimEnd())
console.log(gameName.localeCompare('radhika'))
console.log(gameName.localeCompare('Radhika', 'en', { sensitivity: 'base' }))
console.log(gameName.localeCompare('radhika', 'en', { sensitivity: 'accent' }))
console.log(gameName.localeCompare('radhika', 'en', { sensitivity: 'variant' }))
console.log(gameName.normalize())
console.log(gameName.substring(0,4))